name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        run: sudo xcode-select --switch /Applications/Xcode_12.x.app

      - name: Build and test
        run: |
          xcodebuild clean build test \
            -project .github/GitHubActionsTutorial.xcodeproj \
            -scheme GitHubActionsTutorial \
            -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.0' \
            -enableCodeCoverage YES \
            | xcbeautify

      - name: Generate code coverage report
        run: |
          xcrun xccov view "$(find . -name '*.xccovreport')" --json >> coverage_report.json

      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: coverage_report.json
