name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xcresulttool
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Build and test
        run: xcodebuild clean build test \
          -project GitHubActionsTutorial.xcodeproj \
          -scheme GitHubActionsTutorial \
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.0' \
          -enableCodeCoverage YES \
          | xcpretty

      - name: Fetch test results
        run: |
          DERIVED_DATA=$(xcodebuild -showBuildSettings | grep -E " OBJROOT =| SYMROOT =" | awk '{print $NF}' | sed -e 's/^[[:space:]]*//')
          TEST_RESULT_BUNDLE=$(find "$DERIVED_DATA" -type d -name "*.xcresult" -print0 | xargs -0 ls -t | head -n1)
          mkdir -p "$PWD/test_results"
          cp -R "$TEST_RESULT_BUNDLE" "$PWD/test_results/"

      - name: Show test coverage summary
        run: |
          xcrun xccov view --report --json "$PWD/test_results/*.xcresult" > "$PWD/test_results/coverage.json"
          cat "$PWD/test_results/coverage.json"

      - name: Upload code coverage
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: ${{ github.workspace }}/test_results
