name: iOS Unit Tests with Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Bundler
      run: |
        sudo gem install bundler
        bundle install

    - name: Build and Test
      run: |
        xcodebuild clean build test \
          -project GitHubActionsTutorial.xcodeproj \
          -scheme GitHubActionsTutorial \
          -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.0' \
          -enableCodeCoverage YES \
          | xcpretty

    - name: Generate Code Coverage Report
      run: |
        xcrun xccov view --report --json "$(find . -name "*.xcresult")" > coverage.json

    - name: Upload Code Coverage Artifact
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage
        path: coverage.json
