name: Unit Tests with Code Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode 14.3
        uses: maxim-lobanov/setup-xcode@v1.5.1
        with: xcode-version: latest-stable

      - name: Build and Test
        run: |
          xcodebuild clean build test \
            -project GitHubActionsTutorial.xcodeproj \
            -scheme GitHubActionsTutorial \
            -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.0' \
            -enableCodeCoverage YES \
            | xcpretty

      - name: Generate code coverage report
        run: |
          xcrun xccov archive --report --json -o coverage.xccovarchive "$(find . -name '*.xccovreport')"
          xcrun xccov view --report --json coverage.xccovarchive >> coverage_report.json

      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: Code Coverage
          path: coverage_report.json
