name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: '12.x' # Replace with your desired Xcode version

      - name: Build and test
        run: |
          xcodebuild clean build test \
            -workspace YourProject.xcworkspace \
            -scheme YourScheme \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 12' # Replace with your desired simulator

      - name: Collect test results
        run: |
          TEST_RESULT_DIR="$PWD/test_results"
          mkdir "$TEST_RESULT_DIR"
          find "$PWD" -type f -name "*.xcresult" -exec cp -R {} "$TEST_RESULT_DIR" \;
