name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          xcodebuild clean build test \
            -workspace GitHubActionsTutorial.xcworkspace \
            -scheme GitHubActionsTutorial \
            -destination 'platform=iOS Simulator,name=iPhone 12 Pro,OS=15.0' \
            -resultBundlePath TestResults.xcresult

      - name: Generate code coverage report
        run: |
          xcrun xccov view --report --json TestResults.xcresult > coverage.json
          cat coverage.json

      - name: Upload code coverage report
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: coverage.json
