name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and test
        run: |
          xcodebuild clean build test \
            -project GitHubActionsTutorial.xcodeproj \
            -scheme GitHubActionsTutorial \
            -destination 'platform=iOS Simulator,OS=latest,name=iPhone 12' \
            -enableCodeCoverage YES
